global:
  scrape_interval: 15s  # Interval waktu untuk melakukan scraping
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus sendiri
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter untuk metrik sistem
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # Scrape Blackbox Exporter untuk mengukur latency, uptime, dll
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Menggunakan modul bawaan untuk HTTP 2xx response
    static_configs:
      - targets:
          - http://raspberrypi.local  # Ganti dengan URL yang ingin diuji
          - http://grafana.raspberrypi.local
          - http://wireguard.raspberrypi.local
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # Endpoint Blackbox Exporter
